kind = "mobile"
previewPath = "/"
title = "StatusCatch"
version = "1.0.0"
id = "artifacts/statuscatch"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22372

[services.development]
run = "pnpm --filter @workspace/statuscatch run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/statuscatch", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/statuscatch", "run", "serve" ]

[services.env]
PORT = "22372"
BASE_PATH = "/"
