const colors = {
  light: {
    text: "#0F172A",
    tint: "#3B6FE8",
    background: "#F8FAFC",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#3B6FE8",
    primaryForeground: "#FFFFFF",
    secondary: "#F1F5F9",
    secondaryForeground: "#334155",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#EFF6FF",
    accentForeground: "#1D4ED8",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E2E8F0",
    input: "#E2E8F0",
  },
  dark: {
    text: "#E8EEFF",
    tint: "#4F7EF7",
    background: "#0B0F1A",
    foreground: "#E8EEFF",
    card: "#131B2E",
    cardForeground: "#E8EEFF",
    primary: "#4F7EF7",
    primaryForeground: "#FFFFFF",
    secondary: "#1A2440",
    secondaryForeground: "#B8C8E0",
    muted: "#1A2440",
    mutedForeground: "#6B84A8",
    accent: "#1A3060",
    accentForeground: "#93BBFD",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E2D48",
    input: "#1E2D48",
  },
  radius: 12,
};

export default colors;
